include:
  - project: cencosud-ds/cencommerce/utils/pipe-templates
    ref: master
    file: deploy-to-k8s.yml
stages:
  - init
  - test
  - check
  - build
  - package
  - sast
  - validate-jira
  - deploy
  - dast
  - compliance-jira
  - result-security

staging:
  stage: deploy
  allow_failure: true

.install_dependencies: &install_dependencies
  stage: init
  image: registry.gitlab.com/cencosud-ds/cencommerce/utils/docker-images/node:16.18.0-alpine3.16
  script:
    - npm config set -- //gitlab.com/api/v4/packages/npm/:_authToken=$NPM_TOKEN
    - echo 'npm token ---> npm config set -- //gitlab.com/api/v4/packages/npm/:_authToken='$NPM_TOKEN
    - NODE_ENV=  yarn install # install dependencies
  artifacts:
    paths:
      - node_modules/
    expire_in: 30 minutes
  tags:
    - private
    - ccom
    - staging

.lint: &lint
  stage: test
  image: registry.gitlab.com/cencosud-ds/cencommerce/utils/docker-images/node:16.18.0-alpine3.16
  script:
    - yarn run lint
  tags:
    - private
    - ccom
    - staging

######JOB: INSTALLL
install dependencies:
  <<: *install_dependencies

######JOB: Linter
linter:
  <<: *lint
  dependencies:
    - install dependencies
######LLamado a la imagen de docker
pkg:container:
  stage: package
  extends: .docker
  environment:
    name: staging
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
  variables:
    BUILD_IMAGE_EXTRA_ARGS: '--build-arg NEXT_PUBLIC_ACCOUNT_URI=$NEXT_PUBLIC_ACCOUNT_URI --build-arg NPM_TOKEN=$NPM_TOKEN --build-arg NEW_RELIC_APP_NAME=$NEW_RELIC_APP_NAME --build-arg NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY --build-arg NEW_RELIC_LABELS=$NEW_RELIC_LABELS --build-arg NEXT_PUBLIC_HOME_URI=$NEXT_PUBLIC_HOME_URI --build-arg NEXT_PUBLIC_CART_URI=$NEXT_PUBLIC_CART_URI --build-arg NEXT_PUBLIC_HEADER_URI=$NEXT_PUBLIC_HEADER_URI --build-arg NEXT_PUBLIC_PLP_URI=$NEXT_PUBLIC_PLP_URI --build-arg NEXT_PUBLIC_PDP_URI=$NEXT_PUBLIC_PDP_URI --build-arg NEXT_PUBLIC_BFF_MOBILE_URL=$NEXT_PUBLIC_BFF_MOBILE_URL --build-arg NEXT_PUBLIC_CMS_URL=$NEXT_PUBLIC_CMS_URL --build-arg NEXT_PUBLIC_CMS_API_KEY=$NEXT_PUBLIC_CMS_API_KEY --build-arg NEXT_PUBLIC_VTEX_GRAPHQL=$NEXT_PUBLIC_VTEX_GRAPHQL --build-arg NEXT_PUBLIC_ENHANCEMENT=$NEXT_PUBLIC_ENHANCEMENT --build-arg NEXT_PUBLIC_HOST=$NEXT_PUBLIC_HOST --build-arg NEXT_PUBLIC_GTM_ID=$NEXT_PUBLIC_GTM_ID --build-arg NEXT_PUBLIC_ORDERPLACED_URI=$NEXT_PUBLIC_ORDERPLACED_URI --build-arg NEXT_PUBLIC_GRAPHQL_BACK_URL=$NEXT_PUBLIC_GRAPHQL_BACK_URL --build-arg NEXT_PUBLIC_BFF_WEB_URL=$NEXT_PUBLIC_BFF_WEB_URL'

pkg:production:
  stage: package
  extends: .docker
  environment:
    name: production
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  variables:
    BUILD_IMAGE_EXTRA_ARGS: '--build-arg NEXT_PUBLIC_ACCOUNT_URI=$NEXT_PUBLIC_ACCOUNT_URI --build-arg NPM_TOKEN=$NPM_TOKEN --build-arg NEW_RELIC_APP_NAME=$NEW_RELIC_APP_NAME --build-arg NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY --build-arg NEW_RELIC_LABELS=$NEW_RELIC_LABELS --build-arg NEXT_PUBLIC_HOME_URI=$NEXT_PUBLIC_HOME_URI --build-arg NEXT_PUBLIC_CART_URI=$NEXT_PUBLIC_CART_URI --build-arg NEXT_PUBLIC_HEADER_URI=$NEXT_PUBLIC_HEADER_URI --build-arg NEXT_PUBLIC_PLP_URI=$NEXT_PUBLIC_PLP_URI --build-arg NEXT_PUBLIC_PDP_URI=$NEXT_PUBLIC_PDP_URI --build-arg NEXT_PUBLIC_BFF_MOBILE_URL=$NEXT_PUBLIC_BFF_MOBILE_URL --build-arg NEXT_PUBLIC_CMS_URL=$NEXT_PUBLIC_CMS_URL --build-arg NEXT_PUBLIC_CMS_API_KEY=$NEXT_PUBLIC_CMS_API_KEY --build-arg NEXT_PUBLIC_VTEX_GRAPHQL=$NEXT_PUBLIC_VTEX_GRAPHQL --build-arg NEXT_PUBLIC_ENHANCEMENT=$NEXT_PUBLIC_ENHANCEMENT --build-arg NEXT_PUBLIC_HOST=$NEXT_PUBLIC_HOST --build-arg NEXT_PUBLIC_GTM_ID=$NEXT_PUBLIC_GTM_ID --build-arg PUBLIC_ENDPOINT=$PUBLIC_ENDPOINT --build-arg NEXT_PUBLIC_ORDERPLACED_URI=$NEXT_PUBLIC_ORDERPLACED_URI --build-arg NEXT_PUBLIC_GRAPHQL_BACK_URL=$NEXT_PUBLIC_GRAPHQL_BACK_URL --build-arg NEXT_PUBLIC_BFF_WEB_URL=$NEXT_PUBLIC_BFF_WEB_URL'
