declare module 'headerFooter/*';
declare module 'home/*';
declare module 'confirmation/*';
declare module 'legals/*';
declare module 'account/*';
declare module 'cart/*';
declare module 'pdp/*';
declare module 'plp/*';
declare module 'newrelic';
