export enum SHOPPING_CART_EVENTS {
  CART_ID = 'CART_ID',
  GET_CART_ID = 'GET_CART_ID',
  GET_SHOPPING_CART = 'GET_SHOPPING_CART',
  ADD_ITEM_SHOPPING_CART = 'ADD_ITEM_SHOPPING_CART',
  UPDATE_ITEM_SHOPPING_CART = 'UPDATE_ITEM_SHOPPING_CART',
  REMOVE_ITEM_SHOPPING_CART = 'REMOVE_ITEM_SHOPPING_CART',
  REMOVE_ALL_ITEMS_SHOPPING_CART = 'REMOVE_ALL_ITEMS_SHOPPING_CART',
  UPDATE_SHOPPING_CART = 'UPDATE_SHOPPING_CART',
  IS_LOADING_SHOPPING_CART = 'IS_LOADING_SHOPPING_CART',
  DISPATCH_GET_CART_ID = 'DISPATCH_GET_CART_ID',
  SIMULATE_ADD_PRODUCT = 'SIMULATE_ADD_PRODUCT',
}
