export enum AUTH_EVENTS {
  DISPATCH_LOGOUT = 'DISPATCH_LOGOUT',
  DISPATCH_SIGNIN = 'DISPATCH_SIGNIN',
  DISPATCH_SIGNUP = 'DISPATCH_SIGNUP',
  DISPATCH_SIGNIN_PASSWORD = 'DISPATCH_SIGNIN_PASSWORD',
  GET_SIGNUP_SUCCESS = 'GET_SIGNUP_SUCCESS',
}
